// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloudPolicy.proto

#ifndef PROTOBUF_cloudPolicy_2eproto__INCLUDED
#define PROTOBUF_cloudPolicy_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace com {
namespace cloudscreen {
namespace log {
class CloudPolicyLog;
class CloudPolicyLogDefaultTypeInternal;
extern CloudPolicyLogDefaultTypeInternal _CloudPolicyLog_default_instance_;
}  // namespace log
}  // namespace cloudscreen
}  // namespace com

namespace com {
namespace cloudscreen {
namespace log {

namespace protobuf_cloudPolicy_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cloudPolicy_2eproto

// ===================================================================

class CloudPolicyLog : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.cloudscreen.log.CloudPolicyLog) */ {
 public:
  CloudPolicyLog();
  virtual ~CloudPolicyLog();

  CloudPolicyLog(const CloudPolicyLog& from);

  inline CloudPolicyLog& operator=(const CloudPolicyLog& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CloudPolicyLog(CloudPolicyLog&& from) noexcept
    : CloudPolicyLog() {
    *this = ::std::move(from);
  }

  inline CloudPolicyLog& operator=(CloudPolicyLog&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CloudPolicyLog& default_instance();

  static inline const CloudPolicyLog* internal_default_instance() {
    return reinterpret_cast<const CloudPolicyLog*>(
               &_CloudPolicyLog_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CloudPolicyLog* other);
  friend void swap(CloudPolicyLog& a, CloudPolicyLog& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CloudPolicyLog* New() const PROTOBUF_FINAL { return New(NULL); }

  CloudPolicyLog* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CloudPolicyLog& from);
  void MergeFrom(const CloudPolicyLog& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CloudPolicyLog* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string policy_name = 20;
  void clear_policy_name();
  static const int kPolicyNameFieldNumber = 20;
  const ::std::string& policy_name() const;
  void set_policy_name(const ::std::string& value);
  #if LANG_CXX11
  void set_policy_name(::std::string&& value);
  #endif
  void set_policy_name(const char* value);
  void set_policy_name(const char* value, size_t size);
  ::std::string* mutable_policy_name();
  ::std::string* release_policy_name();
  void set_allocated_policy_name(::std::string* policy_name);

  // string csp_product_name = 80;
  void clear_csp_product_name();
  static const int kCspProductNameFieldNumber = 80;
  const ::std::string& csp_product_name() const;
  void set_csp_product_name(const ::std::string& value);
  #if LANG_CXX11
  void set_csp_product_name(::std::string&& value);
  #endif
  void set_csp_product_name(const char* value);
  void set_csp_product_name(const char* value, size_t size);
  ::std::string* mutable_csp_product_name();
  ::std::string* release_csp_product_name();
  void set_allocated_csp_product_name(::std::string* csp_product_name);

  // string event_name = 100;
  void clear_event_name();
  static const int kEventNameFieldNumber = 100;
  const ::std::string& event_name() const;
  void set_event_name(const ::std::string& value);
  #if LANG_CXX11
  void set_event_name(::std::string&& value);
  #endif
  void set_event_name(const char* value);
  void set_event_name(const char* value, size_t size);
  ::std::string* mutable_event_name();
  ::std::string* release_event_name();
  void set_allocated_event_name(::std::string* event_name);

  // string session_id = 110;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 110;
  const ::std::string& session_id() const;
  void set_session_id(const ::std::string& value);
  #if LANG_CXX11
  void set_session_id(::std::string&& value);
  #endif
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  ::std::string* mutable_session_id();
  ::std::string* release_session_id();
  void set_allocated_session_id(::std::string* session_id);

  // string traffic_id = 120;
  void clear_traffic_id();
  static const int kTrafficIdFieldNumber = 120;
  const ::std::string& traffic_id() const;
  void set_traffic_id(const ::std::string& value);
  #if LANG_CXX11
  void set_traffic_id(::std::string&& value);
  #endif
  void set_traffic_id(const char* value);
  void set_traffic_id(const char* value, size_t size);
  ::std::string* mutable_traffic_id();
  ::std::string* release_traffic_id();
  void set_allocated_traffic_id(::std::string* traffic_id);

  // string matched_device_name = 140;
  void clear_matched_device_name();
  static const int kMatchedDeviceNameFieldNumber = 140;
  const ::std::string& matched_device_name() const;
  void set_matched_device_name(const ::std::string& value);
  #if LANG_CXX11
  void set_matched_device_name(::std::string&& value);
  #endif
  void set_matched_device_name(const char* value);
  void set_matched_device_name(const char* value, size_t size);
  ::std::string* mutable_matched_device_name();
  ::std::string* release_matched_device_name();
  void set_allocated_matched_device_name(::std::string* matched_device_name);

  // string matched_map_name = 160;
  void clear_matched_map_name();
  static const int kMatchedMapNameFieldNumber = 160;
  const ::std::string& matched_map_name() const;
  void set_matched_map_name(const ::std::string& value);
  #if LANG_CXX11
  void set_matched_map_name(::std::string&& value);
  #endif
  void set_matched_map_name(const char* value);
  void set_matched_map_name(const char* value, size_t size);
  ::std::string* mutable_matched_map_name();
  ::std::string* release_matched_map_name();
  void set_allocated_matched_map_name(::std::string* matched_map_name);

  // string matched_net_name = 180;
  void clear_matched_net_name();
  static const int kMatchedNetNameFieldNumber = 180;
  const ::std::string& matched_net_name() const;
  void set_matched_net_name(const ::std::string& value);
  #if LANG_CXX11
  void set_matched_net_name(::std::string&& value);
  #endif
  void set_matched_net_name(const char* value);
  void set_matched_net_name(const char* value, size_t size);
  ::std::string* mutable_matched_net_name();
  ::std::string* release_matched_net_name();
  void set_allocated_matched_net_name(::std::string* matched_net_name);

  // string frequency_name = 183;
  void clear_frequency_name();
  static const int kFrequencyNameFieldNumber = 183;
  const ::std::string& frequency_name() const;
  void set_frequency_name(const ::std::string& value);
  #if LANG_CXX11
  void set_frequency_name(::std::string&& value);
  #endif
  void set_frequency_name(const char* value);
  void set_frequency_name(const char* value, size_t size);
  ::std::string* mutable_frequency_name();
  ::std::string* release_frequency_name();
  void set_allocated_frequency_name(::std::string* frequency_name);

  // string policy = 190;
  void clear_policy();
  static const int kPolicyFieldNumber = 190;
  const ::std::string& policy() const;
  void set_policy(const ::std::string& value);
  #if LANG_CXX11
  void set_policy(::std::string&& value);
  #endif
  void set_policy(const char* value);
  void set_policy(const char* value, size_t size);
  ::std::string* mutable_policy();
  ::std::string* release_policy();
  void set_allocated_policy(::std::string* policy);

  // string trigger_time = 200;
  void clear_trigger_time();
  static const int kTriggerTimeFieldNumber = 200;
  const ::std::string& trigger_time() const;
  void set_trigger_time(const ::std::string& value);
  #if LANG_CXX11
  void set_trigger_time(::std::string&& value);
  #endif
  void set_trigger_time(const char* value);
  void set_trigger_time(const char* value, size_t size);
  ::std::string* mutable_trigger_time();
  ::std::string* release_trigger_time();
  void set_allocated_trigger_time(::std::string* trigger_time);

  // string comment = 220;
  void clear_comment();
  static const int kCommentFieldNumber = 220;
  const ::std::string& comment() const;
  void set_comment(const ::std::string& value);
  #if LANG_CXX11
  void set_comment(::std::string&& value);
  #endif
  void set_comment(const char* value);
  void set_comment(const char* value, size_t size);
  ::std::string* mutable_comment();
  ::std::string* release_comment();
  void set_allocated_comment(::std::string* comment);

  // string reserve_content1 = 240;
  void clear_reserve_content1();
  static const int kReserveContent1FieldNumber = 240;
  const ::std::string& reserve_content1() const;
  void set_reserve_content1(const ::std::string& value);
  #if LANG_CXX11
  void set_reserve_content1(::std::string&& value);
  #endif
  void set_reserve_content1(const char* value);
  void set_reserve_content1(const char* value, size_t size);
  ::std::string* mutable_reserve_content1();
  ::std::string* release_reserve_content1();
  void set_allocated_reserve_content1(::std::string* reserve_content1);

  // string reserve_content2 = 260;
  void clear_reserve_content2();
  static const int kReserveContent2FieldNumber = 260;
  const ::std::string& reserve_content2() const;
  void set_reserve_content2(const ::std::string& value);
  #if LANG_CXX11
  void set_reserve_content2(::std::string&& value);
  #endif
  void set_reserve_content2(const char* value);
  void set_reserve_content2(const char* value, size_t size);
  ::std::string* mutable_reserve_content2();
  ::std::string* release_reserve_content2();
  void set_allocated_reserve_content2(::std::string* reserve_content2);

  // uint64 matched_policy_id = 10;
  void clear_matched_policy_id();
  static const int kMatchedPolicyIdFieldNumber = 10;
  ::google::protobuf::uint64 matched_policy_id() const;
  void set_matched_policy_id(::google::protobuf::uint64 value);

  // uint32 log_type = 30;
  void clear_log_type();
  static const int kLogTypeFieldNumber = 30;
  ::google::protobuf::uint32 log_type() const;
  void set_log_type(::google::protobuf::uint32 value);

  // uint32 delivery_type = 40;
  void clear_delivery_type();
  static const int kDeliveryTypeFieldNumber = 40;
  ::google::protobuf::uint32 delivery_type() const;
  void set_delivery_type(::google::protobuf::uint32 value);

  // uint32 action_taken = 210;
  void clear_action_taken();
  static const int kActionTakenFieldNumber = 210;
  ::google::protobuf::uint32 action_taken() const;
  void set_action_taken(::google::protobuf::uint32 value);

  // uint64 enterprise_id = 52;
  void clear_enterprise_id();
  static const int kEnterpriseIdFieldNumber = 52;
  ::google::protobuf::uint64 enterprise_id() const;
  void set_enterprise_id(::google::protobuf::uint64 value);

  // uint64 user_id = 55;
  void clear_user_id();
  static const int kUserIdFieldNumber = 55;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // uint64 device_activity_id = 60;
  void clear_device_activity_id();
  static const int kDeviceActivityIdFieldNumber = 60;
  ::google::protobuf::uint64 device_activity_id() const;
  void set_device_activity_id(::google::protobuf::uint64 value);

  // uint64 csp_product_id = 70;
  void clear_csp_product_id();
  static const int kCspProductIdFieldNumber = 70;
  ::google::protobuf::uint64 csp_product_id() const;
  void set_csp_product_id(::google::protobuf::uint64 value);

  // uint64 event_id = 90;
  void clear_event_id();
  static const int kEventIdFieldNumber = 90;
  ::google::protobuf::uint64 event_id() const;
  void set_event_id(::google::protobuf::uint64 value);

  // uint64 event_category_id = 91;
  void clear_event_category_id();
  static const int kEventCategoryIdFieldNumber = 91;
  ::google::protobuf::uint64 event_category_id() const;
  void set_event_category_id(::google::protobuf::uint64 value);

  // uint32 severity = 50;
  void clear_severity();
  static const int kSeverityFieldNumber = 50;
  ::google::protobuf::uint32 severity() const;
  void set_severity(::google::protobuf::uint32 value);

  // uint32 threshold = 185;
  void clear_threshold();
  static const int kThresholdFieldNumber = 185;
  ::google::protobuf::uint32 threshold() const;
  void set_threshold(::google::protobuf::uint32 value);

  // uint64 matched_device_id = 130;
  void clear_matched_device_id();
  static const int kMatchedDeviceIdFieldNumber = 130;
  ::google::protobuf::uint64 matched_device_id() const;
  void set_matched_device_id(::google::protobuf::uint64 value);

  // uint64 matched_map_id = 150;
  void clear_matched_map_id();
  static const int kMatchedMapIdFieldNumber = 150;
  ::google::protobuf::uint64 matched_map_id() const;
  void set_matched_map_id(::google::protobuf::uint64 value);

  // uint64 matched_net_id = 170;
  void clear_matched_net_id();
  static const int kMatchedNetIdFieldNumber = 170;
  ::google::protobuf::uint64 matched_net_id() const;
  void set_matched_net_id(::google::protobuf::uint64 value);

  // uint64 frequency_id = 182;
  void clear_frequency_id();
  static const int kFrequencyIdFieldNumber = 182;
  ::google::protobuf::uint64 frequency_id() const;
  void set_frequency_id(::google::protobuf::uint64 value);

  // uint32 period = 187;
  void clear_period();
  static const int kPeriodFieldNumber = 187;
  ::google::protobuf::uint32 period() const;
  void set_period(::google::protobuf::uint32 value);

  // uint32 period_unit = 189;
  void clear_period_unit();
  static const int kPeriodUnitFieldNumber = 189;
  ::google::protobuf::uint32 period_unit() const;
  void set_period_unit(::google::protobuf::uint32 value);

  // uint64 reserve_id1 = 230;
  void clear_reserve_id1();
  static const int kReserveId1FieldNumber = 230;
  ::google::protobuf::uint64 reserve_id1() const;
  void set_reserve_id1(::google::protobuf::uint64 value);

  // uint64 reserve_id2 = 250;
  void clear_reserve_id2();
  static const int kReserveId2FieldNumber = 250;
  ::google::protobuf::uint64 reserve_id2() const;
  void set_reserve_id2(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:com.cloudscreen.log.CloudPolicyLog)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr policy_name_;
  ::google::protobuf::internal::ArenaStringPtr csp_product_name_;
  ::google::protobuf::internal::ArenaStringPtr event_name_;
  ::google::protobuf::internal::ArenaStringPtr session_id_;
  ::google::protobuf::internal::ArenaStringPtr traffic_id_;
  ::google::protobuf::internal::ArenaStringPtr matched_device_name_;
  ::google::protobuf::internal::ArenaStringPtr matched_map_name_;
  ::google::protobuf::internal::ArenaStringPtr matched_net_name_;
  ::google::protobuf::internal::ArenaStringPtr frequency_name_;
  ::google::protobuf::internal::ArenaStringPtr policy_;
  ::google::protobuf::internal::ArenaStringPtr trigger_time_;
  ::google::protobuf::internal::ArenaStringPtr comment_;
  ::google::protobuf::internal::ArenaStringPtr reserve_content1_;
  ::google::protobuf::internal::ArenaStringPtr reserve_content2_;
  ::google::protobuf::uint64 matched_policy_id_;
  ::google::protobuf::uint32 log_type_;
  ::google::protobuf::uint32 delivery_type_;
  ::google::protobuf::uint32 action_taken_;
  ::google::protobuf::uint64 enterprise_id_;
  ::google::protobuf::uint64 user_id_;
  ::google::protobuf::uint64 device_activity_id_;
  ::google::protobuf::uint64 csp_product_id_;
  ::google::protobuf::uint64 event_id_;
  ::google::protobuf::uint64 event_category_id_;
  ::google::protobuf::uint32 severity_;
  ::google::protobuf::uint32 threshold_;
  ::google::protobuf::uint64 matched_device_id_;
  ::google::protobuf::uint64 matched_map_id_;
  ::google::protobuf::uint64 matched_net_id_;
  ::google::protobuf::uint64 frequency_id_;
  ::google::protobuf::uint32 period_;
  ::google::protobuf::uint32 period_unit_;
  ::google::protobuf::uint64 reserve_id1_;
  ::google::protobuf::uint64 reserve_id2_;
  mutable int _cached_size_;
  friend struct protobuf_cloudPolicy_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CloudPolicyLog

// uint64 matched_policy_id = 10;
inline void CloudPolicyLog::clear_matched_policy_id() {
  matched_policy_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::matched_policy_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_policy_id)
  return matched_policy_id_;
}
inline void CloudPolicyLog::set_matched_policy_id(::google::protobuf::uint64 value) {
  
  matched_policy_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_policy_id)
}

// string policy_name = 20;
inline void CloudPolicyLog::clear_policy_name() {
  policy_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::policy_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.policy_name)
  return policy_name_.GetNoArena();
}
inline void CloudPolicyLog::set_policy_name(const ::std::string& value) {
  
  policy_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.policy_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_policy_name(::std::string&& value) {
  
  policy_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.policy_name)
}
#endif
inline void CloudPolicyLog::set_policy_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  policy_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.policy_name)
}
inline void CloudPolicyLog::set_policy_name(const char* value, size_t size) {
  
  policy_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.policy_name)
}
inline ::std::string* CloudPolicyLog::mutable_policy_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.policy_name)
  return policy_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_policy_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.policy_name)
  
  return policy_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_policy_name(::std::string* policy_name) {
  if (policy_name != NULL) {
    
  } else {
    
  }
  policy_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), policy_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.policy_name)
}

// uint32 log_type = 30;
inline void CloudPolicyLog::clear_log_type() {
  log_type_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::log_type() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.log_type)
  return log_type_;
}
inline void CloudPolicyLog::set_log_type(::google::protobuf::uint32 value) {
  
  log_type_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.log_type)
}

// uint32 delivery_type = 40;
inline void CloudPolicyLog::clear_delivery_type() {
  delivery_type_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::delivery_type() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.delivery_type)
  return delivery_type_;
}
inline void CloudPolicyLog::set_delivery_type(::google::protobuf::uint32 value) {
  
  delivery_type_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.delivery_type)
}

// uint32 severity = 50;
inline void CloudPolicyLog::clear_severity() {
  severity_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::severity() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.severity)
  return severity_;
}
inline void CloudPolicyLog::set_severity(::google::protobuf::uint32 value) {
  
  severity_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.severity)
}

// uint64 enterprise_id = 52;
inline void CloudPolicyLog::clear_enterprise_id() {
  enterprise_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::enterprise_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.enterprise_id)
  return enterprise_id_;
}
inline void CloudPolicyLog::set_enterprise_id(::google::protobuf::uint64 value) {
  
  enterprise_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.enterprise_id)
}

// uint64 user_id = 55;
inline void CloudPolicyLog::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::user_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.user_id)
  return user_id_;
}
inline void CloudPolicyLog::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.user_id)
}

// uint64 device_activity_id = 60;
inline void CloudPolicyLog::clear_device_activity_id() {
  device_activity_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::device_activity_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.device_activity_id)
  return device_activity_id_;
}
inline void CloudPolicyLog::set_device_activity_id(::google::protobuf::uint64 value) {
  
  device_activity_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.device_activity_id)
}

// uint64 csp_product_id = 70;
inline void CloudPolicyLog::clear_csp_product_id() {
  csp_product_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::csp_product_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.csp_product_id)
  return csp_product_id_;
}
inline void CloudPolicyLog::set_csp_product_id(::google::protobuf::uint64 value) {
  
  csp_product_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.csp_product_id)
}

// string csp_product_name = 80;
inline void CloudPolicyLog::clear_csp_product_name() {
  csp_product_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::csp_product_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
  return csp_product_name_.GetNoArena();
}
inline void CloudPolicyLog::set_csp_product_name(const ::std::string& value) {
  
  csp_product_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_csp_product_name(::std::string&& value) {
  
  csp_product_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
}
#endif
inline void CloudPolicyLog::set_csp_product_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  csp_product_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
}
inline void CloudPolicyLog::set_csp_product_name(const char* value, size_t size) {
  
  csp_product_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
}
inline ::std::string* CloudPolicyLog::mutable_csp_product_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
  return csp_product_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_csp_product_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
  
  return csp_product_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_csp_product_name(::std::string* csp_product_name) {
  if (csp_product_name != NULL) {
    
  } else {
    
  }
  csp_product_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), csp_product_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.csp_product_name)
}

// uint64 event_id = 90;
inline void CloudPolicyLog::clear_event_id() {
  event_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::event_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.event_id)
  return event_id_;
}
inline void CloudPolicyLog::set_event_id(::google::protobuf::uint64 value) {
  
  event_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.event_id)
}

// uint64 event_category_id = 91;
inline void CloudPolicyLog::clear_event_category_id() {
  event_category_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::event_category_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.event_category_id)
  return event_category_id_;
}
inline void CloudPolicyLog::set_event_category_id(::google::protobuf::uint64 value) {
  
  event_category_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.event_category_id)
}

// string event_name = 100;
inline void CloudPolicyLog::clear_event_name() {
  event_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::event_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.event_name)
  return event_name_.GetNoArena();
}
inline void CloudPolicyLog::set_event_name(const ::std::string& value) {
  
  event_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.event_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_event_name(::std::string&& value) {
  
  event_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.event_name)
}
#endif
inline void CloudPolicyLog::set_event_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  event_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.event_name)
}
inline void CloudPolicyLog::set_event_name(const char* value, size_t size) {
  
  event_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.event_name)
}
inline ::std::string* CloudPolicyLog::mutable_event_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.event_name)
  return event_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_event_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.event_name)
  
  return event_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_event_name(::std::string* event_name) {
  if (event_name != NULL) {
    
  } else {
    
  }
  event_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), event_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.event_name)
}

// string session_id = 110;
inline void CloudPolicyLog::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::session_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.session_id)
  return session_id_.GetNoArena();
}
inline void CloudPolicyLog::set_session_id(const ::std::string& value) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.session_id)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_session_id(::std::string&& value) {
  
  session_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.session_id)
}
#endif
inline void CloudPolicyLog::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.session_id)
}
inline void CloudPolicyLog::set_session_id(const char* value, size_t size) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.session_id)
}
inline ::std::string* CloudPolicyLog::mutable_session_id() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.session_id)
  return session_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_session_id() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.session_id)
  
  return session_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_session_id(::std::string* session_id) {
  if (session_id != NULL) {
    
  } else {
    
  }
  session_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.session_id)
}

// string traffic_id = 120;
inline void CloudPolicyLog::clear_traffic_id() {
  traffic_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::traffic_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.traffic_id)
  return traffic_id_.GetNoArena();
}
inline void CloudPolicyLog::set_traffic_id(const ::std::string& value) {
  
  traffic_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.traffic_id)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_traffic_id(::std::string&& value) {
  
  traffic_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.traffic_id)
}
#endif
inline void CloudPolicyLog::set_traffic_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  traffic_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.traffic_id)
}
inline void CloudPolicyLog::set_traffic_id(const char* value, size_t size) {
  
  traffic_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.traffic_id)
}
inline ::std::string* CloudPolicyLog::mutable_traffic_id() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.traffic_id)
  return traffic_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_traffic_id() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.traffic_id)
  
  return traffic_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_traffic_id(::std::string* traffic_id) {
  if (traffic_id != NULL) {
    
  } else {
    
  }
  traffic_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), traffic_id);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.traffic_id)
}

// uint64 matched_device_id = 130;
inline void CloudPolicyLog::clear_matched_device_id() {
  matched_device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::matched_device_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_device_id)
  return matched_device_id_;
}
inline void CloudPolicyLog::set_matched_device_id(::google::protobuf::uint64 value) {
  
  matched_device_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_device_id)
}

// string matched_device_name = 140;
inline void CloudPolicyLog::clear_matched_device_name() {
  matched_device_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::matched_device_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
  return matched_device_name_.GetNoArena();
}
inline void CloudPolicyLog::set_matched_device_name(const ::std::string& value) {
  
  matched_device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_matched_device_name(::std::string&& value) {
  
  matched_device_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
}
#endif
inline void CloudPolicyLog::set_matched_device_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  matched_device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
}
inline void CloudPolicyLog::set_matched_device_name(const char* value, size_t size) {
  
  matched_device_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
}
inline ::std::string* CloudPolicyLog::mutable_matched_device_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
  return matched_device_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_matched_device_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
  
  return matched_device_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_matched_device_name(::std::string* matched_device_name) {
  if (matched_device_name != NULL) {
    
  } else {
    
  }
  matched_device_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), matched_device_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.matched_device_name)
}

// uint64 matched_map_id = 150;
inline void CloudPolicyLog::clear_matched_map_id() {
  matched_map_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::matched_map_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_map_id)
  return matched_map_id_;
}
inline void CloudPolicyLog::set_matched_map_id(::google::protobuf::uint64 value) {
  
  matched_map_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_map_id)
}

// string matched_map_name = 160;
inline void CloudPolicyLog::clear_matched_map_name() {
  matched_map_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::matched_map_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
  return matched_map_name_.GetNoArena();
}
inline void CloudPolicyLog::set_matched_map_name(const ::std::string& value) {
  
  matched_map_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_matched_map_name(::std::string&& value) {
  
  matched_map_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
}
#endif
inline void CloudPolicyLog::set_matched_map_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  matched_map_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
}
inline void CloudPolicyLog::set_matched_map_name(const char* value, size_t size) {
  
  matched_map_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
}
inline ::std::string* CloudPolicyLog::mutable_matched_map_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
  return matched_map_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_matched_map_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
  
  return matched_map_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_matched_map_name(::std::string* matched_map_name) {
  if (matched_map_name != NULL) {
    
  } else {
    
  }
  matched_map_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), matched_map_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.matched_map_name)
}

// uint64 matched_net_id = 170;
inline void CloudPolicyLog::clear_matched_net_id() {
  matched_net_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::matched_net_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_net_id)
  return matched_net_id_;
}
inline void CloudPolicyLog::set_matched_net_id(::google::protobuf::uint64 value) {
  
  matched_net_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_net_id)
}

// string matched_net_name = 180;
inline void CloudPolicyLog::clear_matched_net_name() {
  matched_net_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::matched_net_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
  return matched_net_name_.GetNoArena();
}
inline void CloudPolicyLog::set_matched_net_name(const ::std::string& value) {
  
  matched_net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_matched_net_name(::std::string&& value) {
  
  matched_net_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
}
#endif
inline void CloudPolicyLog::set_matched_net_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  matched_net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
}
inline void CloudPolicyLog::set_matched_net_name(const char* value, size_t size) {
  
  matched_net_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
}
inline ::std::string* CloudPolicyLog::mutable_matched_net_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
  return matched_net_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_matched_net_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
  
  return matched_net_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_matched_net_name(::std::string* matched_net_name) {
  if (matched_net_name != NULL) {
    
  } else {
    
  }
  matched_net_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), matched_net_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.matched_net_name)
}

// uint64 frequency_id = 182;
inline void CloudPolicyLog::clear_frequency_id() {
  frequency_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::frequency_id() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.frequency_id)
  return frequency_id_;
}
inline void CloudPolicyLog::set_frequency_id(::google::protobuf::uint64 value) {
  
  frequency_id_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.frequency_id)
}

// string frequency_name = 183;
inline void CloudPolicyLog::clear_frequency_name() {
  frequency_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::frequency_name() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.frequency_name)
  return frequency_name_.GetNoArena();
}
inline void CloudPolicyLog::set_frequency_name(const ::std::string& value) {
  
  frequency_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.frequency_name)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_frequency_name(::std::string&& value) {
  
  frequency_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.frequency_name)
}
#endif
inline void CloudPolicyLog::set_frequency_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frequency_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.frequency_name)
}
inline void CloudPolicyLog::set_frequency_name(const char* value, size_t size) {
  
  frequency_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.frequency_name)
}
inline ::std::string* CloudPolicyLog::mutable_frequency_name() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.frequency_name)
  return frequency_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_frequency_name() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.frequency_name)
  
  return frequency_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_frequency_name(::std::string* frequency_name) {
  if (frequency_name != NULL) {
    
  } else {
    
  }
  frequency_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frequency_name);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.frequency_name)
}

// uint32 threshold = 185;
inline void CloudPolicyLog::clear_threshold() {
  threshold_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::threshold() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.threshold)
  return threshold_;
}
inline void CloudPolicyLog::set_threshold(::google::protobuf::uint32 value) {
  
  threshold_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.threshold)
}

// uint32 period = 187;
inline void CloudPolicyLog::clear_period() {
  period_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::period() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.period)
  return period_;
}
inline void CloudPolicyLog::set_period(::google::protobuf::uint32 value) {
  
  period_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.period)
}

// uint32 period_unit = 189;
inline void CloudPolicyLog::clear_period_unit() {
  period_unit_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::period_unit() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.period_unit)
  return period_unit_;
}
inline void CloudPolicyLog::set_period_unit(::google::protobuf::uint32 value) {
  
  period_unit_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.period_unit)
}

// string policy = 190;
inline void CloudPolicyLog::clear_policy() {
  policy_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::policy() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.policy)
  return policy_.GetNoArena();
}
inline void CloudPolicyLog::set_policy(const ::std::string& value) {
  
  policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.policy)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_policy(::std::string&& value) {
  
  policy_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.policy)
}
#endif
inline void CloudPolicyLog::set_policy(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.policy)
}
inline void CloudPolicyLog::set_policy(const char* value, size_t size) {
  
  policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.policy)
}
inline ::std::string* CloudPolicyLog::mutable_policy() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.policy)
  return policy_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_policy() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.policy)
  
  return policy_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_policy(::std::string* policy) {
  if (policy != NULL) {
    
  } else {
    
  }
  policy_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), policy);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.policy)
}

// string trigger_time = 200;
inline void CloudPolicyLog::clear_trigger_time() {
  trigger_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::trigger_time() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.trigger_time)
  return trigger_time_.GetNoArena();
}
inline void CloudPolicyLog::set_trigger_time(const ::std::string& value) {
  
  trigger_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.trigger_time)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_trigger_time(::std::string&& value) {
  
  trigger_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.trigger_time)
}
#endif
inline void CloudPolicyLog::set_trigger_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  trigger_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.trigger_time)
}
inline void CloudPolicyLog::set_trigger_time(const char* value, size_t size) {
  
  trigger_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.trigger_time)
}
inline ::std::string* CloudPolicyLog::mutable_trigger_time() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.trigger_time)
  return trigger_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_trigger_time() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.trigger_time)
  
  return trigger_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_trigger_time(::std::string* trigger_time) {
  if (trigger_time != NULL) {
    
  } else {
    
  }
  trigger_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), trigger_time);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.trigger_time)
}

// uint32 action_taken = 210;
inline void CloudPolicyLog::clear_action_taken() {
  action_taken_ = 0u;
}
inline ::google::protobuf::uint32 CloudPolicyLog::action_taken() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.action_taken)
  return action_taken_;
}
inline void CloudPolicyLog::set_action_taken(::google::protobuf::uint32 value) {
  
  action_taken_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.action_taken)
}

// string comment = 220;
inline void CloudPolicyLog::clear_comment() {
  comment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::comment() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.comment)
  return comment_.GetNoArena();
}
inline void CloudPolicyLog::set_comment(const ::std::string& value) {
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.comment)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_comment(::std::string&& value) {
  
  comment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.comment)
}
#endif
inline void CloudPolicyLog::set_comment(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.comment)
}
inline void CloudPolicyLog::set_comment(const char* value, size_t size) {
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.comment)
}
inline ::std::string* CloudPolicyLog::mutable_comment() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.comment)
  return comment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_comment() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.comment)
  
  return comment_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_comment(::std::string* comment) {
  if (comment != NULL) {
    
  } else {
    
  }
  comment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), comment);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.comment)
}

// uint64 reserve_id1 = 230;
inline void CloudPolicyLog::clear_reserve_id1() {
  reserve_id1_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::reserve_id1() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.reserve_id1)
  return reserve_id1_;
}
inline void CloudPolicyLog::set_reserve_id1(::google::protobuf::uint64 value) {
  
  reserve_id1_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.reserve_id1)
}

// string reserve_content1 = 240;
inline void CloudPolicyLog::clear_reserve_content1() {
  reserve_content1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::reserve_content1() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
  return reserve_content1_.GetNoArena();
}
inline void CloudPolicyLog::set_reserve_content1(const ::std::string& value) {
  
  reserve_content1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_reserve_content1(::std::string&& value) {
  
  reserve_content1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
}
#endif
inline void CloudPolicyLog::set_reserve_content1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reserve_content1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
}
inline void CloudPolicyLog::set_reserve_content1(const char* value, size_t size) {
  
  reserve_content1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
}
inline ::std::string* CloudPolicyLog::mutable_reserve_content1() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
  return reserve_content1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_reserve_content1() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
  
  return reserve_content1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_reserve_content1(::std::string* reserve_content1) {
  if (reserve_content1 != NULL) {
    
  } else {
    
  }
  reserve_content1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reserve_content1);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.reserve_content1)
}

// uint64 reserve_id2 = 250;
inline void CloudPolicyLog::clear_reserve_id2() {
  reserve_id2_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CloudPolicyLog::reserve_id2() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.reserve_id2)
  return reserve_id2_;
}
inline void CloudPolicyLog::set_reserve_id2(::google::protobuf::uint64 value) {
  
  reserve_id2_ = value;
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.reserve_id2)
}

// string reserve_content2 = 260;
inline void CloudPolicyLog::clear_reserve_content2() {
  reserve_content2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CloudPolicyLog::reserve_content2() const {
  // @@protoc_insertion_point(field_get:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
  return reserve_content2_.GetNoArena();
}
inline void CloudPolicyLog::set_reserve_content2(const ::std::string& value) {
  
  reserve_content2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
}
#if LANG_CXX11
inline void CloudPolicyLog::set_reserve_content2(::std::string&& value) {
  
  reserve_content2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
}
#endif
inline void CloudPolicyLog::set_reserve_content2(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reserve_content2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
}
inline void CloudPolicyLog::set_reserve_content2(const char* value, size_t size) {
  
  reserve_content2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
}
inline ::std::string* CloudPolicyLog::mutable_reserve_content2() {
  
  // @@protoc_insertion_point(field_mutable:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
  return reserve_content2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CloudPolicyLog::release_reserve_content2() {
  // @@protoc_insertion_point(field_release:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
  
  return reserve_content2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CloudPolicyLog::set_allocated_reserve_content2(::std::string* reserve_content2) {
  if (reserve_content2 != NULL) {
    
  } else {
    
  }
  reserve_content2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reserve_content2);
  // @@protoc_insertion_point(field_set_allocated:com.cloudscreen.log.CloudPolicyLog.reserve_content2)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace log
}  // namespace cloudscreen
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cloudPolicy_2eproto__INCLUDED
